# Generated by Django 6.0 on 2026-01-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='plaintext',
        ),
        migrations.AddField(
            model_name='submission',
            name='client_pubkey_pem',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='encrypted_text',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='nonce',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='salt',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
