# Generated by Django 5.0.7 on 2026-01-17 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_submission_options_remove_submission_plaintext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',), 'verbose_name': 'Encrypted Submission', 'verbose_name_plural': 'Encrypted Submissions'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='client_pubkey_pem',
            field=models.BinaryField(help_text='Client ECC public key in PEM format'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='encrypted_text',
            field=models.BinaryField(help_text='AES-GCM encrypted message payload'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nonce',
            field=models.BinaryField(help_text='AES-GCM nonce (12 bytes)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='salt',
            field=models.BinaryField(help_text='HKDF salt used for AES key derivation'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
