# Generated by Django 5.0.7 on 2026-01-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_submission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='client_pubkey_pem',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='encrypted_text',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nonce',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='salt',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='DecryptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.submission')),
            ],
            options={
                'verbose_name': 'Decryption Audit Log',
                'verbose_name_plural': 'Decryption Audit Logs',
                'ordering': ('-decrypted_at',),
            },
        ),
    ]
