# Generated by Django 5.0.7 on 2026-01-21 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_submission_client_pubkey_pem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decryptionauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='decryptionauditlog',
            old_name='decrypted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='decryptionauditlog',
            name='reason',
            field=models.TextField(default='Legacy audit entry (reason not recorded)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decryptionauditlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decryptionauditlog',
            name='ip_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='decryptionauditlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.submission'),
        ),
    ]
